/*
 * API for interacting with GameStonks
 *
 * GameStonks API 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	DataApiService := openapi.NewDataApiService()
	DataApiController := openapi.NewDataApiController(DataApiService)

	StockApiService := openapi.NewStockApiService()
	StockApiController := openapi.NewStockApiController(StockApiService)

	router := openapi.NewRouter(DataApiController, StockApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
