/*
 * API for interacting with GameStonks
 *
 * GameStonks API 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// DataApiRouter defines the required methods for binding the api requests to a responses for the DataApi
// The DataApiRouter implementation should parse necessary information from the http request, 
// pass the data to a DataApiServicer to perform the required actions, then write the service results to the http response.
type DataApiRouter interface { 
	GetMostVoted(http.ResponseWriter, *http.Request)
	GetStockCommentMostUsedWordsAndFrequency(http.ResponseWriter, *http.Request)
	GetStockCommentPerformance(http.ResponseWriter, *http.Request)
	GetStockFinancialPerformance(http.ResponseWriter, *http.Request)
	GetStockVotesPerDayPerformance(http.ResponseWriter, *http.Request)
}
// StockApiRouter defines the required methods for binding the api requests to a responses for the StockApi
// The StockApiRouter implementation should parse necessary information from the http request, 
// pass the data to a StockApiServicer to perform the required actions, then write the service results to the http response.
type StockApiRouter interface { 
	AddNewComment(http.ResponseWriter, *http.Request)
	AddNewVote(http.ResponseWriter, *http.Request)
	GetAllStocks(http.ResponseWriter, *http.Request)
	GetIndividualStock(http.ResponseWriter, *http.Request)
	InsertIndividualStock(http.ResponseWriter, *http.Request)
}


// DataApiServicer defines the api actions for the DataApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type DataApiServicer interface { 
	GetMostVoted(context.Context, string, string, string) (ImplResponse, error)
	GetStockCommentMostUsedWordsAndFrequency(context.Context, string) (ImplResponse, error)
	GetStockCommentPerformance(context.Context, string, string, string) (ImplResponse, error)
	GetStockFinancialPerformance(context.Context, string) (ImplResponse, error)
	GetStockVotesPerDayPerformance(context.Context, string, string, string) (ImplResponse, error)
}


// StockApiServicer defines the api actions for the StockApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type StockApiServicer interface { 
	AddNewComment(context.Context, string) (ImplResponse, error)
	AddNewVote(context.Context, string) (ImplResponse, error)
	GetAllStocks(context.Context, string, string) (ImplResponse, error)
	GetIndividualStock(context.Context, string) (ImplResponse, error)
	InsertIndividualStock(context.Context, string) (ImplResponse, error)
}
