/*
 * API for interacting with GameStonks
 *
 * GameStonks API 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DataApiService is a service that implents the logic for the DataApiServicer
// This service should implement the business logic for every endpoint for the DataApi API. 
// Include any external packages or services that will be required by this service.
type DataApiService struct {
}

// NewDataApiService creates a default api service
func NewDataApiService() DataApiServicer {
	return &DataApiService{}
}

// GetMostVoted - Gets all stocks on the platform within a date range
func (s *DataApiService) GetMostVoted(ctx context.Context, voteFloor string, since string, until string) (ImplResponse, error) {
	// TODO - update GetMostVoted with the required logic for this service method.
	// Add api_data_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetMostVoted method not implemented")
}

// GetStockCommentMostUsedWordsAndFrequency - Get most used words in comments for a given stock
func (s *DataApiService) GetStockCommentMostUsedWordsAndFrequency(ctx context.Context, stockTicker string) (ImplResponse, error) {
	// TODO - update GetStockCommentMostUsedWordsAndFrequency with the required logic for this service method.
	// Add api_data_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetStockCommentMostUsedWordsAndFrequency method not implemented")
}

// GetStockCommentPerformance - Gets stock comments per day trend
func (s *DataApiService) GetStockCommentPerformance(ctx context.Context, stockTicker string, since string, until string) (ImplResponse, error) {
	// TODO - update GetStockCommentPerformance with the required logic for this service method.
	// Add api_data_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetStockCommentPerformance method not implemented")
}

// GetStockFinancialPerformance - Gets stock finance performance data
func (s *DataApiService) GetStockFinancialPerformance(ctx context.Context, stockTicker string) (ImplResponse, error) {
	// TODO - update GetStockFinancialPerformance with the required logic for this service method.
	// Add api_data_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetStockFinancialPerformance method not implemented")
}

// GetStockVotesPerDayPerformance - Gets votes per day trend from a stock
func (s *DataApiService) GetStockVotesPerDayPerformance(ctx context.Context, stockTicker string, since string, until string) (ImplResponse, error) {
	// TODO - update GetStockVotesPerDayPerformance with the required logic for this service method.
	// Add api_data_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetStockVotesPerDayPerformance method not implemented")
}

